//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Cursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_shrnEntities : DbContext
    {
        public gr691_shrnEntities()
            : base("name=gr691_shrnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRPO_Basket> TRPO_Basket { get; set; }
        public virtual DbSet<TRPO_Client> TRPO_Client { get; set; }
        public virtual DbSet<TRPO_Employee> TRPO_Employee { get; set; }
        public virtual DbSet<TRPO_Order> TRPO_Order { get; set; }
        public virtual DbSet<TRPO_Product> TRPO_Product { get; set; }
        public virtual DbSet<TRPO_Product_Type> TRPO_Product_Type { get; set; }
        public virtual DbSet<TRPO_Provider> TRPO_Provider { get; set; }
        public virtual DbSet<TRPO_Role> TRPO_Role { get; set; }
        public virtual DbSet<TRPO_Status> TRPO_Status { get; set; }
        public virtual DbSet<TRPO_User> TRPO_User { get; set; }
    }
}
