//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Cursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRPO_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRPO_Product()
        {
            this.TRPO_Basket = new HashSet<TRPO_Basket>();
        }
    
        public int id_product { get; set; }
        public string name { get; set; }
        public int id_product_type { get; set; }
        public int id_provider { get; set; }
        public decimal price { get; set; }
        public int quantity_warehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRPO_Basket> TRPO_Basket { get; set; }
        public virtual TRPO_Product_Type TRPO_Product_Type { get; set; }
        public virtual TRPO_Provider TRPO_Provider { get; set; }
    }
}
