//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Cursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRPO_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRPO_Order()
        {
            this.TRPO_Basket = new HashSet<TRPO_Basket>();
        }
    
        public int id_order { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_employee { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> price_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRPO_Basket> TRPO_Basket { get; set; }
        public virtual TRPO_Client TRPO_Client { get; set; }
        public virtual TRPO_Employee TRPO_Employee { get; set; }
    }
}
