//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO_Cursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRPO_Basket
    {
        public int id_basket { get; set; }
        public int id_product { get; set; }
        public Nullable<int> id_order { get; set; }
        public int quantity { get; set; }
        public decimal total { get; set; }
        public int id_user { get; set; }
        public int id_status { get; set; }
    
        public virtual TRPO_Order TRPO_Order { get; set; }
        public virtual TRPO_Product TRPO_Product { get; set; }
        public virtual TRPO_Status TRPO_Status { get; set; }
        public virtual TRPO_User TRPO_User { get; set; }
    }
}
